"""Repeat runs on one checkout must not degrade to INCONCLUSIVE.

A build or test run routinely rewrites a tracked lockfile: `go test` refreshes
`go.work.sum`, cargo touches `Cargo.lock`. The precondition guard - correctly -
refuses to run against a dirty tree, so if we leave our own dirt behind, the
*second* PR anyone verifies in the same clone answers INCONCLUSIVE for a reason
that has nothing to do with that PR. Found while scouting knadh/koanf: four
PRs, the first verified, the next three aborted on a `go.work.sum` we had
modified ourselves.
"""

from __future__ import annotations

import subprocess

from coretexa_verify import gitops
from coretexa_verify.models import Report, Verdict
from coretexa_verify.verify import _restore_files_we_dirtied


def _git(repo, *args):
    subprocess.run(["git", "-C", str(repo), *args], check=True, capture_output=True)


def _repo(tmp_path):
    repo = tmp_path / "r"
    repo.mkdir()
    _git(repo, "init", "-q")
    _git(repo, "config", "user.email", "t@t")
    _git(repo, "config", "user.name", "t")
    (repo / "lock.sum").write_text("original\n")
    (repo / "src.go").write_text("package main\n")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-qm", "init")
    return repo


def test_restores_a_lockfile_the_test_run_rewrote(tmp_path):
    repo = _repo(tmp_path)
    baseline = gitops.TreeState.capture(repo)
    assert gitops.is_clean(repo)

    # stand in for `go test` refreshing go.work.sum
    (repo / "lock.sum").write_text("regenerated by the build\n")
    assert not gitops.is_clean(repo)

    report = Report(verdict=Verdict.INCONCLUSIVE, headline="")
    _restore_files_we_dirtied(str(repo), baseline, report)

    assert (repo / "lock.sum").read_text() == "original\n"
    assert gitops.is_clean(repo), "a second run would have aborted on our own dirt"
    assert report.tree_restored is True
    assert report.warnings == []


def test_leaves_alone_what_was_already_dirty(tmp_path):
    """Only files dirtied *after* the baseline are ours to revert.

    This is the direction that matters for safety: the guard runs before the
    baseline is taken, but if that ever changes, a user's real uncommitted work
    must not be silently thrown away by our cleanup.
    """
    repo = _repo(tmp_path)
    (repo / "src.go").write_text("package main // the user's unsaved work\n")
    baseline = gitops.TreeState.capture(repo)

    (repo / "lock.sum").write_text("regenerated\n")

    _restore_files_we_dirtied(str(repo), baseline, Report(verdict=Verdict.INCONCLUSIVE, headline=""))

    assert (repo / "lock.sum").read_text() == "original\n"
    assert "unsaved work" in (repo / "src.go").read_text()


def test_no_op_on_a_clean_tree(tmp_path):
    repo = _repo(tmp_path)
    baseline = gitops.TreeState.capture(repo)
    report = Report(verdict=Verdict.INCONCLUSIVE, headline="")

    _restore_files_we_dirtied(str(repo), baseline, report)

    assert report.warnings == []
    assert report.tree_restored is True
