"""`cargo test` runner.

Cargo has no stable machine-readable test output. ``--format json`` is a
nightly-only libtest flag and ``cargo test --message-format json`` describes the
*build*, not the tests. So this runner parses libtest's stable text output,
which has been the same two shapes for a decade:

    test gitignore::tests::ig_escaped_trailing_space ... ok
    test result: ok. 186 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

That is enough for everything the tool needs. ``cargo-nextest`` is preferred
when it happens to be installed, because it writes real JUnit XML, but it is
never required - the text parser is the default path and the one that is
exercised by the unit tests.

Three Rust-specific facts drive the rest of this module.

**Tests live inside source files.** The idiomatic Rust unit test is a
``#[cfg(test)] mod tests`` block at the bottom of the module it tests, so one
file is both the code under test and the test. That is handled by
:mod:`coretexa_verify.inline_tests`, which reverts such a file hunk by hunk and
leaves the test hunks at head. Without it, every Rust PR of this shape would
either destroy its own evidence or be unrunnable.

**Compile errors are the interesting failure.** Reverting a source file that a
new test calls into does not produce an assertion failure - it produces
``error[E0599]: no method named ...``. Detecting that as ``BUILD_ERROR`` (rather
than as a generic non-zero exit) is what makes ``GATE_HOLDS_BUILD`` mean "the
tests gate the presence of the new API".

**Ignored is skipped.** ``#[ignore]`` tests report as ``ignored``; they are
counted as skipped and therefore excluded from the executed count, so a
selection that is entirely ``#[ignore]``d can never produce a verdict.

Build artefacts
---------------

Like ``go test``, ``cargo test`` *is* the build: it compiles the crate and its
dependencies from source on every invocation and its fingerprint includes the
mtime and hash of each source file, so a reverted ``.rs`` file is recompiled
before the test binary is linked. ``build.rs`` output, ``include_str!`` data and
``CARGO_BIN_EXE_*`` binaries are all regenerated by that same invocation. There
is therefore no separate build step to re-run and no stale artefact a test could
read instead of the reverted source - :meth:`detect_build_step` returns None and
:meth:`artifact_risk` returns ``""`` as statements about cargo, not as gaps.

The price is time: a cold compile of a large crate is minutes, not seconds,
which is why :data:`DEFAULT_TIMEOUT` is deliberately generous and is surfaced in
the report.
"""

from __future__ import annotations

import os
import posixpath
import re
import shutil

from ..gitops import run
from ..models import Outcome, TestRunResult
from .base import DetectionContext, Runner

#: Compiling a real crate tree from cold is minutes. The default per-run timeout
#: is raised accordingly and is reported, so a TIMEOUT verdict is never mistaken
#: for a finding about the code.
DEFAULT_TIMEOUT = 900

#: `test some::path ... ok`
TEST_LINE = re.compile(
    r"^test\s+(?P<name>\S+?)(?:\s+-\s+should\s+panic)?\s+\.\.\.\s+(?P<status>ok|FAILED|ignored|"
    r"benchmarked)\b"
)
#: `test result: ok. 3 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out`
RESULT_LINE = re.compile(
    r"^test result:\s+(?P<verdict>\w+)\.\s+(?P<passed>\d+)\s+passed;\s+(?P<failed>\d+)\s+failed;"
    r"\s+(?P<ignored>\d+)\s+ignored"
)
#: `error[E0599]: no method named ...` - a compile error, not a test failure.
RUSTC_CODED_ERROR = re.compile(r"^error\[(?P<code>E\d{4})\]:", re.MULTILINE)
#: A diagnostic with no error code, e.g. `error: expected one of ...`.
RUSTC_BARE_ERROR = re.compile(r"^error:\s*(?P<text>.*)$", re.MULTILINE)

#: Lines that are cargo/rustc *summarising* the errors above rather than
#: reporting a new one. Counting them inflates the error count by one per
#: crate, which was enough to make a hand-checked "8 E0599" read as 9.
ERROR_SUMMARY_FRAGMENTS = (
    "could not compile",
    "aborting due to",
    "build failed",
)


def _count_rustc_errors(blob: str) -> tuple[int, list[str]]:
    """``(error count, distinct error codes)`` for one cargo invocation.

    Coded diagnostics win when there are any: ``error[E0599]`` is one real
    problem, whereas ``error: could not compile `gtk4` due to 8 previous
    errors`` is cargo restating those same eight. Only when nothing carries a
    code do uncoded diagnostics get counted, and the summary lines are excluded
    either way.
    """
    coded = RUSTC_CODED_ERROR.findall(blob)
    if coded:
        return len(coded), sorted(set(coded))
    bare = [
        text
        for text in RUSTC_BARE_ERROR.findall(blob)
        if not any(fragment in text for fragment in ERROR_SUMMARY_FRAGMENTS)
    ]
    return len(bare), []

#: Cargo/rustc failures that happen before any test binary exists.
BUILD_FAILURE_MARKERS = (
    "could not compile",
    "aborting due to",
    "error: linking with",
    "failed to run custom build command",
    "error: failed to select a version",
    "error: no such command",
)

#: `#[test]`-ish attribute immediately above a `fn name(`.
RUST_TEST_FN = re.compile(
    r"#\[(?:[\w:]*\b(?:test|bench|rstest|test_case|proptest|quickcheck)\b)[^\]]*\]"
    r"(?P<between>(?:\s*(?:#\[[^\]]*\]|//[^\n]*)\s*)*)\s*"
    r"(?:pub\s+)?(?:async\s+)?(?:unsafe\s+)?fn\s+(?P<name>\w+)"
)

#: `mod name {` - used to build the `a::b::test_name` path libtest reports.
RUST_MOD = re.compile(r"^\s*(?:pub(?:\([^)]*\))?\s+)?mod\s+(\w+)\s*\{", re.MULTILINE)


# --------------------------------------------------------------------------
# manifests
# --------------------------------------------------------------------------


def _read(path: str) -> str:
    try:
        with open(path, encoding="utf-8", errors="replace") as fh:
            return fh.read(200_000)
    except OSError:
        return ""


def crate_name(manifest_text: str) -> str:
    """``name`` from the ``[package]`` table of a Cargo.toml, or ``""``.

    Parsed with a small line scan rather than a TOML library: this tool has no
    runtime dependencies and supports Python 3.9, where ``tomllib`` does not
    exist. Only the ``[package] name`` field is needed.
    """
    in_package = False
    for raw in manifest_text.splitlines():
        line = raw.strip()
        if line.startswith("["):
            in_package = line.replace(" ", "") == "[package]"
            continue
        if not in_package or "=" not in line or line.startswith("#"):
            continue
        key, _, value = line.partition("=")
        if key.strip() == "name":
            return value.strip().strip(",").strip().strip('"').strip("'")
    return ""


def is_workspace_root(manifest_text: str) -> bool:
    return any(line.strip().replace(" ", "") == "[workspace]" for line in manifest_text.splitlines())


def owning_manifest(repo: str, rel_path: str) -> str:
    """Nearest ancestor directory of ``rel_path`` with a package Cargo.toml.

    A virtual manifest (a ``[workspace]`` table with no ``[package]``) is not an
    owner - it declares members, it does not contain code - so the walk keeps
    going up past it only if it has no ``[package]`` of its own.
    """
    parts = rel_path.replace("\\", "/").split("/")[:-1]
    while parts:
        candidate = "/".join(parts)
        manifest = os.path.join(repo, candidate, "Cargo.toml")
        if os.path.exists(manifest) and crate_name(_read(manifest)):
            return candidate
        parts.pop()
    root = os.path.join(repo, "Cargo.toml")
    if os.path.exists(root) and crate_name(_read(root)):
        return ""
    return ""


# --------------------------------------------------------------------------
# parsing
# --------------------------------------------------------------------------


def parse_cargo_test_text(
    stdout: str, exit_code: int, stderr: str = ""
) -> TestRunResult:
    """Parse stable ``cargo test`` output into a :class:`TestRunResult`.

    Compile errors are checked *first and separately* from the test counts. A
    crate that does not compile prints ``error[E0599]`` to stderr and produces
    no ``test result:`` line at all; if we looked only at counts we would see
    zero of everything and call it ``NO_TESTS_RUN``, which reads as "nothing to
    say" when the truth is "the tests could not be built without the change" -
    the strongest gate signal there is.
    """
    blob = (stdout or "") + "\n" + (stderr or "")

    passed = failed = ignored = 0
    failing: list[str] = []
    saw_result_line = False

    for line in blob.splitlines():
        line = line.strip()
        m = TEST_LINE.match(line)
        if m:
            if m.group("status") == "FAILED":
                failing.append(m.group("name"))
            continue
        m = RESULT_LINE.match(line)
        if m:
            saw_result_line = True
            passed += int(m.group("passed"))
            failed += int(m.group("failed"))
            ignored += int(m.group("ignored"))

    n_errors, codes = _count_rustc_errors(blob)
    marker = next((m for m in BUILD_FAILURE_MARKERS if m in blob), "")

    # A compile failure before any test binary ran: no `test result:` line was
    # produced, but rustc had things to say. This is the gtk4-rs shape - revert
    # the source, keep the test, get eight E0599s.
    if not saw_result_line and (n_errors or marker):
        detail = f" ({n_errors} rustc error(s)"
        if codes:
            detail += ": " + ", ".join(codes[:6])
        detail += ")"
        return TestRunResult(
            command=[],
            outcome=Outcome.BUILD_ERROR,
            exit_code=exit_code,
            errored=max(n_errors, 1),
            total=max(n_errors, 1),
            erroring_ids=[c for c in codes[:50]] or ["<compile error>"],
            note=(
                f"the crate did not compile, so no test binary was produced and no assertion "
                f"was exercised{detail}"
                + (f"; {marker}" if marker else "")
            ),
        )

    if not saw_result_line:
        if exit_code == 0:
            return TestRunResult(
                command=[], outcome=Outcome.NO_TESTS_RUN, exit_code=exit_code,
                note="cargo test produced no `test result:` line and no error",
            )
        return TestRunResult(
            command=[], outcome=Outcome.RUNNER_ERROR, exit_code=exit_code,
            note=f"cargo test exited {exit_code} without producing a parseable test summary",
        )

    total = passed + failed + ignored
    if total == 0:
        return TestRunResult(
            command=[], outcome=Outcome.NO_TESTS_RUN, exit_code=exit_code,
            note="cargo test ran but the filter matched no tests",
        )

    if failed:
        outcome, note = Outcome.ASSERT_FAIL, ""
    elif n_errors or marker:
        # Some binaries ran and some crate failed to build: report the build
        # break, because a partial run cannot be called a pass.
        outcome = Outcome.BUILD_ERROR
        note = f"some tests ran but the build also reported {n_errors} rustc error(s)"
    elif exit_code == 0:
        outcome, note = Outcome.PASS, ""
    else:
        outcome = Outcome.RUNNER_ERROR
        note = f"all reported tests passed but cargo exited {exit_code}"

    return TestRunResult(
        command=[],
        outcome=outcome,
        exit_code=exit_code,
        passed=passed,
        failed=failed,
        errored=0,
        # `#[ignore]` is Rust's skip. Excluded from `executed`, so a selection
        # that is entirely ignored can never back a verdict.
        skipped=ignored,
        total=total,
        failing_ids=failing[:50],
        note=note,
    )


# --------------------------------------------------------------------------
# narrowing helpers
# --------------------------------------------------------------------------


def rust_test_paths(text: str) -> list[tuple[str, str, int]]:
    """``(bare name, module path, line)`` for each ``#[test]`` function.

    libtest reports a unit test as ``module::path::fn_name``, so the enclosing
    ``mod`` chain has to be reconstructed to build a filter that matches. The
    brace tracking reuses the same code-aware scanner the inline-test region
    finder uses, so braces inside strings and comments do not shift the chain.
    """
    from ..inline_tests import code_mask

    mask = code_mask(text)
    # depth -> module name entered at that depth
    stack: list[tuple[int, str]] = []
    depth = 0
    out: list[tuple[str, str, int]] = []

    mod_at: dict[int, str] = {}
    for m in RUST_MOD.finditer(text):
        if mask[m.start()]:
            mod_at[m.end() - 1] = m.group(1)  # index of the `{`

    test_at: dict[int, str] = {}
    for m in RUST_TEST_FN.finditer(text):
        if mask[m.start()]:
            test_at[m.start()] = m.group("name")

    for i, ch in enumerate(text):
        if i in test_at:
            path = "::".join(name for _, name in stack)
            line = text.count("\n", 0, i) + 1
            out.append((test_at[i], f"{path}::{test_at[i]}" if path else test_at[i], line))
        if not mask[i]:
            continue
        if ch == "{":
            depth += 1
            if i in mod_at:
                stack.append((depth, mod_at[i]))
        elif ch == "}":
            if stack and stack[-1][0] == depth:
                stack.pop()
            depth -= 1
    return out


def module_prefix(crate_relative_path: str) -> str:
    """The libtest module path a file's tests are reported under.

    libtest names a unit test ``<module path>::<fn>``, and a file's own module
    path comes from where it sits in the crate, not from anything written
    inside it. ``src/gitignore.rs`` contributes ``gitignore``; ``src/lib.rs``
    contributes nothing; ``src/a/mod.rs`` contributes ``a``. Getting this wrong
    is invisible - the filter simply matches no test and the run reports
    NO_TESTS_RUN - so it is worth spelling out.

    Integration tests under ``tests/`` are each their own crate root, so they
    have no prefix.
    """
    path = crate_relative_path.replace("\\", "/")
    if path.startswith(("tests/", "benches/", "examples/")):
        return ""
    if path.startswith("src/"):
        path = path[len("src/"):]
    if path in ("lib.rs", "main.rs"):
        return ""
    if path.endswith("/mod.rs"):
        path = path[: -len("/mod.rs")]
    elif path.endswith(".rs"):
        path = path[:-3]
    return path.replace("/", "::")


def find_test_spans(text: str) -> list[tuple[str, str, int, int]]:
    """``(name, module path, first line, last line)`` per ``#[test]`` function.

    The end of each function is found by matching its opening brace, not by
    running up to the next test. That distinction matters: anything between two
    test functions - a helper, a macro invocation that generates more tests -
    would otherwise be silently attributed to the test above it.
    """
    from ..inline_tests import _match_bracket, code_mask

    mask = code_mask(text)
    spans: list[tuple[str, str, int, int]] = []
    for name, full, start in rust_test_paths(text):
        offset = 0
        for _ in range(start - 1):
            offset = text.index("\n", offset) + 1
        brace = offset
        while brace < len(text) and not (mask[brace] and text[brace] == "{"):
            brace += 1
        end_off = _match_bracket(text, mask, brace, "{", "}") if brace < len(text) else -1
        end = text.count("\n", 0, end_off - 1) + 1 if end_off != -1 else start
        spans.append((name, full, start, max(end, start)))
    return spans


#: A macro invocation sitting where an item would go: `ignored!(...)`,
#: `glib::wrapper! { ... }`. Such a macro can expand to any number of
#: `#[test] fn`s whose names appear nowhere in the source.
ITEM_MACRO = re.compile(r"^\s*(?:pub\s+)?[a-z_]\w*(?:::\w+)*!\s*[\[({]")


def region_generates_tests_by_macro(text: str, regions: list[tuple[int, int]]) -> str:
    """The first item-position macro invocation inside a test region, or ``""``.

    A macro that expands into tests makes source-level narrowing unsafe: the
    generated test names are not in the file, so keeping "only the ``#[test]
    fn``s the diff touched" would quietly drop the very cases the PR added.
    ripgrep's gitignore tests are exactly this - ``ignored!(...)`` and
    ``not_ignored!(...)`` generate one test each - so the runner declines to
    narrow rather than measuring the wrong thing.
    """
    from ..inline_tests import code_mask

    mask = code_mask(text)
    lines = text.splitlines()
    offset = 0
    for idx, raw in enumerate(lines, start=1):
        line_start = offset
        offset += len(raw) + 1
        if not any(lo <= idx <= hi for lo, hi in regions):
            continue
        visible = "".join(
            raw[k] if line_start + k < len(mask) and mask[line_start + k] else " "
            for k in range(len(raw))
        )
        if ITEM_MACRO.match(visible):
            return visible.strip()
    return ""


# --------------------------------------------------------------------------
# runner
# --------------------------------------------------------------------------


class CargoTestRunner(Runner):
    """`cargo test --no-fail-fast`, scoped to the crate that owns the change.

    Target spelling (the runner owns it end to end):

    * ``ignore``                       - the whole crate's tests
    * ``ignore#gitignore_skip_bom``    - one integration binary (``tests/*.rs``)
    * ``ignore::gitignore::tests::foo``- one lib test, by libtest filter
    * ``ignore#bin::case``             - one test inside one integration binary

    ``::`` marks a narrowed target, which is the convention verify.py uses to
    decide what counts as running "a whole file or directory" - so cargo gets
    the same max-targets accounting as pytest for free.
    """

    id = "cargo-test"
    language = "rust"
    test_file_extensions = (".rs",)
    report_suffix = "xml"

    def __init__(self, repo: str, reason: str, extra_args=None, nextest: bool = False):
        super().__init__(repo, reason, extra_args)
        self.nextest = nextest

    # -- target parsing ----------------------------------------------------
    @staticmethod
    def _parse_target(target: str) -> tuple[str, str, str]:
        """``crate``, ``integration binary or ""``, ``libtest filter or ""``."""
        head, sep, filt = target.partition("::")
        crate, hsep, binary = head.partition("#")
        return crate, (binary if hsep else ""), (filt if sep else "")

    def build_command(self, targets: list[str], report_path: str) -> list[str]:
        crates: list[str] = []
        binaries: list[str] = []
        filters: list[str] = []
        for target in targets:
            crate, binary, filt = self._parse_target(target)
            if crate and crate not in crates:
                crates.append(crate)
            if binary and binary not in binaries:
                binaries.append(binary)
            if filt and filt not in filters:
                filters.append(filt)

        argv = ["cargo", "test", "--no-fail-fast"]
        for crate in crates:
            argv += ["-p", crate]
        for binary in binaries:
            argv += ["--test", binary]
        argv += self.extra_args

        # libtest accepts several positional filters (they are OR-ed) and
        # `--exact` makes each one match a whole test path rather than a
        # substring. Passing the names unanchored would let `foo` also select
        # `foo_regression`, which would quietly widen the very selection we
        # went to the trouble of narrowing.
        if filters:
            argv += ["--", "--exact", *filters]
        return argv

    def parse(self, report_path: str, exit_code: int, stdout: str, stderr: str) -> TestRunResult:
        return parse_cargo_test_text(stdout, exit_code, stderr)

    def default_test_dir(self) -> str | None:
        return None

    def subprocess_env(self) -> dict:
        env = super().subprocess_env()
        # Colour codes would break the line regexes; cargo honours this even
        # when something downstream thinks it is on a tty.
        env["CARGO_TERM_COLOR"] = "never"
        env["RUST_BACKTRACE"] = "0"
        return env

    # -- build artefacts ---------------------------------------------------
    def detect_build_step(self, timeout: int) -> None:
        """None: ``cargo test`` compiles the crate itself. See the module docstring."""
        return None

    def artifact_risk(self, targets: list[str], source_paths: list[str]) -> str:
        """Empty: cargo rebuilds from source on every ``cargo test``."""
        return ""

    # -- path -> crate spec ------------------------------------------------
    def focus(self, targets: list[str]) -> tuple[list[str], str] | None:
        """Turn repo-relative file paths into cargo crate specs.

        ``-p <crate>`` is used rather than changing directory, so a workspace
        member is addressed the same way whether the repository is a workspace
        or a single crate, and ``cwd`` stays at the manifest root where the
        lockfile lives.
        """
        out: list[str] = []
        crates: list[str] = []
        mapped = False
        for target in targets:
            path, sep, filt = target.partition("::")
            if "/" not in path and not path.endswith(".rs"):
                if target not in out:
                    out.append(target)
                continue
            mapped = True
            owner = owning_manifest(self.repo, path)
            manifest = os.path.join(self.repo, owner, "Cargo.toml") if owner else os.path.join(self.repo, "Cargo.toml")
            name = crate_name(_read(manifest))
            if not name:
                return None
            if name not in crates:
                crates.append(name)
            rel = posixpath.relpath(path, owner) if owner else path
            if rel.startswith("tests/") and rel.endswith(".rs"):
                spec = f"{name}#{posixpath.basename(rel)[:-3]}"
            else:
                spec = name
            if sep and filt:
                spec = f"{spec}::{filt}"
            if spec not in out:
                out.append(spec)
        if not mapped:
            return None
        return out, (
            f"cargo selects tests by crate, not by path, so the changed file(s) were mapped to "
            f"the nearest owning Cargo.toml and run with -p {' -p '.join(crates)}"
        )

    # -- enumeration -------------------------------------------------------
    def collect(self, targets: list[str], timeout: int, extra=None) -> list[str] | None:
        """``cargo test -- --list``. Returns None when the compile is too slow.

        Enumeration costs a full compile, which for a large crate exceeds the
        (deliberately short) refinement timeout. Returning None then switches
        selection refinement off rather than blocking the run - narrowing for
        Rust comes from :meth:`narrow_from_diff`, which needs no compile.
        """
        if any("/" in t or t.endswith(".rs") for t in targets):
            # Still in file-path space: focus() has not run yet, so there is no
            # crate to name. Burning a full compile on a command cargo would
            # reject helps nobody.
            return None
        crates: list[str] = []
        for target in targets:
            crate, _, _ = self._parse_target(target)
            if crate and crate not in crates:
                crates.append(crate)
        if not crates:
            return None
        argv = ["cargo", "test", "--no-fail-fast"]
        for crate in crates:
            argv += ["-p", crate]
        argv += ["--", "--list"]
        res = run(argv, cwd=self.cwd, timeout=timeout, env=self.subprocess_env(), isolate=True)
        if res.timed_out or res.returncode != 0:
            return None
        ids: list[str] = []
        for line in res.stdout.splitlines():
            line = line.strip()
            if line.endswith(": test") or line.endswith(": benchmark"):
                name = line.rsplit(":", 1)[0].strip()
                nid = f"{crates[0]}::{name}"
                if nid not in ids:
                    ids.append(nid)
        return ids or None

    # -- narrowing ---------------------------------------------------------
    def narrow_from_diff(self, repo, base_sha, head_sha, path, targets):
        """Keep only the ``#[test]`` functions whose body the diff touched."""
        if not path.endswith(".rs"):
            return None
        from .. import refine
        from ..hunks import read_head_text

        from ..inline_tests import find_regions

        head_text = read_head_text(repo, head_sha, path)
        if not head_text:
            return None
        changed = refine.changed_line_numbers(repo, base_sha, head_sha, path)
        if not changed:
            return None

        # A macro that generates tests makes narrowing unsafe - see
        # region_generates_tests_by_macro. Decline rather than measure a subset
        # we cannot show is the whole of what the PR added.
        regions = find_regions(path, head_text) or [(1, head_text.count("\n") + 1)]
        macro = region_generates_tests_by_macro(head_text, regions)
        if macro:
            return None

        spans = find_test_spans(head_text)
        if not spans:
            return None
        hit = [
            (name, full)
            for name, full, start, end in spans
            if changed & set(range(start, end + 1))
        ]
        if not hit or len(hit) == len(spans):
            # None of them, or all of them: narrowing would add nothing.
            return None

        # libtest reports `<file's module path>::<in-file module path>::<fn>`.
        owner = owning_manifest(repo, path)
        rel = posixpath.relpath(path, owner) if owner else path
        prefix = module_prefix(rel)
        qualified = [(name, f"{prefix}::{full}" if prefix else full) for name, full in hit]

        out = []
        for target in targets:
            base = target.partition("::")[0]
            for _, full in qualified:
                nid = f"{base}::{full}"
                if nid not in out:
                    out.append(nid)
        hit = qualified
        names = [name for name, _ in hit]
        return (
            out,
            f"only the {len(hit)} test function(s) this PR added or modified "
            f"({', '.join(names[:5])})",
            (
                f"the changed lines of {path} fall inside these #[test] fn declarations in the "
                f"head revision, and cargo was narrowed to them with "
                f"`-- --exact {' '.join(full for _, full in hit[:3])}`"
            ),
        )


# --------------------------------------------------------------------------


def detect_rust(ctx: DetectionContext, extra_args=None) -> Runner | None:
    """Pick the cargo runner, or return None if this is not a cargo project."""
    if not ctx.exists("Cargo.toml"):
        return None
    if not shutil.which("cargo"):
        return None

    manifest = ctx.read("Cargo.toml")
    shape = "workspace" if is_workspace_root(manifest) else "package"
    nextest = bool(shutil.which("cargo-nextest"))
    reason = (
        f"found Cargo.toml ({shape}) -> `cargo test --no-fail-fast`"
        + ("; cargo-nextest is installed but the stable text parser is used by default" if nextest else "")
    )
    runner = CargoTestRunner(ctx.repo, reason=reason, extra_args=extra_args, nextest=nextest)
    runner.setup_warnings.append(
        f"cargo compiles the crate and its dependencies on every test run, so each of the "
        f"runs this tool performs can take minutes from cold; the per-run timeout is "
        f"{DEFAULT_TIMEOUT}s by default and a TIMEOUT is reported as INCONCLUSIVE, never as a "
        f"finding"
    )
    return runner
